/**
 * OpenAPI 3.0 export using openapi3-ts builders.
 * 
 * Pulls data from the database, applies schema intelligence,
 * and produces a validated OpenAPI 3.0.3 specification.
 */

import {
  OpenApiBuilder,
  PathItemObject,
  OperationObject,
  ParameterObject,
  ResponseObject,
  SchemaObject,
  MediaTypeObject,
  InfoObject,
  ServerObject,
} from 'openapi3-ts/oas30';
import { getDb } from '../db/schema';
import { getAllEndpoints, EndpointRecord } from '../db/endpoints';
import { extractPathParams } from '../schema/path-folder';
import { inferSchema, mergeSchemas, JSONSchemaFragment } from '../schema/infer';

export interface ExportOptions {
  baseUrl: string;
  title?: string;
  version?: string;
  description?: string;
  onlyApproved?: boolean;
  validate?: boolean;
}

/**
 * Convert our internal JSONSchemaFragment to an OpenAPI SchemaObject.
 */
function toOasSchema(fragment: JSONSchemaFragment): SchemaObject {
  if (!fragment || (!fragment.type && !fragment.oneOf && !fragment.nullable)) {
    return {};
  }

  const schema: SchemaObject = {};

  if (fragment.type) schema.type = fragment.type as any;
  if (fragment.format) schema.format = fragment.format;
  if (fragment.nullable) schema.nullable = true;
  if (fragment.enum) schema.enum = fragment.enum;
  if (fragment.description) schema.description = fragment.description;

  if (fragment.items) {
    schema.items = toOasSchema(fragment.items);
  }

  if (fragment.properties) {
    schema.properties = {};
    for (const [key, value] of Object.entries(fragment.properties)) {
      schema.properties[key] = toOasSchema(value);
    }
  }

  if (fragment.required && fragment.required.length > 0) {
    schema.required = fragment.required;
  }

  if (fragment.oneOf) {
    schema.oneOf = fragment.oneOf.map(toOasSchema);
  }

  return schema;
}

/**
 * Gather response schemas for an endpoint from captured requests.
 */
function getResponseSchemas(endpointId: string): Record<number, JSONSchemaFragment> {
  const db = getDb();

  // Check if schemas table has merged schemas
  const mergedSchemas = db.prepare(`
    SELECT status_code, schema_json FROM schemas
    WHERE endpoint_id = ? AND merged = 1
  `).all(endpointId) as any[];

  if (mergedSchemas.length > 0) {
    const result: Record<number, JSONSchemaFragment> = {};
    for (const row of mergedSchemas) {
      try {
        result[row.status_code] = JSON.parse(row.schema_json);
      } catch {}
    }
    return result;
  }

  // Fallback: infer from raw requests
  const requests = db.prepare(`
    SELECT r.response_status, r.response_body
    FROM requests r
    JOIN request_endpoint_map rem ON r.id = rem.request_id
    WHERE rem.endpoint_id = ? AND r.response_body IS NOT NULL
  `).all(endpointId) as any[];

  const schemasByStatus: Record<number, JSONSchemaFragment[]> = {};

  for (const req of requests) {
    const status = req.response_status;
    if (!status) continue;

    let body: any;
    try {
      body = typeof req.response_body === 'string'
        ? JSON.parse(req.response_body)
        : req.response_body;
    } catch {
      continue;
    }

    if (body && typeof body === 'object') {
      if (!schemasByStatus[status]) schemasByStatus[status] = [];
      schemasByStatus[status].push(inferSchema(body));
    }
  }

  // Merge all schemas for each status code
  const result: Record<number, JSONSchemaFragment> = {};
  for (const [status, schemas] of Object.entries(schemasByStatus)) {
    result[parseInt(status)] = schemas.reduce((acc, s) => mergeSchemas(acc, s));
  }

  return result;
}

/**
 * Generate an OpenAPI 3.0 specification from the discovery database.
 */
export function generateOpenAPISpec(options: ExportOptions): object {
  const {
    baseUrl,
    title = 'Auto-Discovered API',
    version = '1.0.0',
    description = 'API specification generated by ApiGen',
    onlyApproved = false,
  } = options;

  // Fetch endpoints from DB
  let endpoints = getAllEndpoints();

  if (onlyApproved) {
    endpoints = endpoints.filter(ep => ep.status === 'approved');
  }

  // Build spec using openapi3-ts
  const builder = OpenApiBuilder.create()
    .addOpenApiVersion('3.0.3')
    .addInfo({
      title,
      version,
      description,
      contact: { name: 'ApiGen' },
    } as InfoObject)
    .addServer({ url: baseUrl } as ServerObject);

  // Group endpoints by path template
  const pathGroups: Record<string, EndpointRecord[]> = {};
  for (const ep of endpoints) {
    if (!pathGroups[ep.path_template]) {
      pathGroups[ep.path_template] = [];
    }
    pathGroups[ep.path_template].push(ep);
  }

  // Build paths
  for (const [pathTemplate, epGroup] of Object.entries(pathGroups)) {
    const pathItem: PathItemObject = {};

    // Extract path parameters once per path
    const paramNames = extractPathParams(pathTemplate);
    const pathParams: ParameterObject[] = paramNames.map(name => ({
      name,
      in: 'path',
      required: true,
      schema: { type: 'string' },
    }));

    for (const ep of epGroup) {
      const method = ep.method.toLowerCase();
      const responseSchemas = getResponseSchemas(ep.id);

      const operation: OperationObject = {
        responses: {},
        ...(ep.tag ? { tags: [ep.tag] } : {}),
        ...(ep.observation_count < 3
          ? { 'x-apigen-low-confidence': true, 'x-apigen-observations': ep.observation_count }
          : {}
        ),
        'x-apigen-source': 'network',
      } as OperationObject;

      // Add path params
      if (pathParams.length > 0) {
        operation.parameters = [...pathParams];
      }

      // Build responses
      if (Object.keys(responseSchemas).length > 0) {
        for (const [statusCode, schema] of Object.entries(responseSchemas)) {
          const mediaType: MediaTypeObject = {
            schema: toOasSchema(schema as JSONSchemaFragment),
          };

          const response: ResponseObject = {
            description: `Response for status ${statusCode}`,
            content: { 'application/json': mediaType },
          };

          operation.responses![statusCode.toString()] = response;
        }
      } else {
        operation.responses!['200'] = { description: 'Success' };
      }

      // Assign to path item
      (pathItem as any)[method] = operation;
    }

    builder.addPath(pathTemplate, pathItem);
  }

  return builder.getSpec();
}

/**
 * Validate an OpenAPI spec object against the 3.0 schema.
 * Returns an array of validation errors (empty = valid).
 */
export function validateSpec(spec: any): string[] {
  const errors: string[] = [];

  // Basic structural validation
  if (!spec.openapi) errors.push('Missing "openapi" version field');
  if (!spec.info) errors.push('Missing "info" object');
  if (!spec.info?.title) errors.push('Missing "info.title"');
  if (!spec.info?.version) errors.push('Missing "info.version"');
  if (!spec.paths) errors.push('Missing "paths" object');

  // Validate each path
  if (spec.paths) {
    for (const [pathStr, pathItem] of Object.entries(spec.paths)) {
      if (!pathStr.startsWith('/')) {
        errors.push(`Path "${pathStr}" must start with /`);
      }

      const validMethods = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'];
      for (const key of Object.keys(pathItem as object)) {
        if (key.startsWith('x-')) continue; // extensions are fine
        if (key === 'parameters' || key === 'summary' || key === 'description') continue;
        if (!validMethods.includes(key)) {
          errors.push(`Path "${pathStr}" has invalid method "${key}"`);
        }
      }
    }
  }

  return errors;
}
