import { MapEntry } from './schema-engine';

function mapSchemaToOpenAPI(customSchema: any): any {
  if (customSchema === 'string') return { type: 'string' };
  if (customSchema === 'number') return { type: 'number' };
  if (customSchema === 'boolean') return { type: 'boolean' };
  if (customSchema === 'null') return { nullable: true };
  if (customSchema === 'any' || customSchema === 'unknown') return {};

  if (Array.isArray(customSchema)) {
    let itemSchema = {};
    if (customSchema.length > 0) {
      itemSchema = mapSchemaToOpenAPI(customSchema[0]);
    }
    return { type: 'array', items: itemSchema };
  }

  if (typeof customSchema === 'object' && customSchema !== null) {
    const properties: any = {};
    for (const [key, value] of Object.entries(customSchema)) {
      properties[key] = mapSchemaToOpenAPI(value);
    }
    return { type: 'object', properties };
  }

  return {};
}

function extractPathParams(path: string): string[] {
  const matches = path.match(/\{([^}]+)\}/g);
  if (!matches) return [];
  return matches.map(m => m.slice(1, -1));
}

export function generateOpenAPI(customSchema: MapEntry[], baseUrl: string): any {
  const openapi: any = {
    openapi: '3.0.0',
    info: {
      title: 'Auto-Discovered API',
      version: '1.0.0',
      description: 'API documentation generated by apigen'
    },
    servers: [
      { url: baseUrl }
    ],
    paths: {}
  };

  for (const entry of customSchema) {
    const method = entry.method.toLowerCase();
    const path = entry.foldedUrl;

    if (!openapi.paths[path]) {
      openapi.paths[path] = {};
    }

    const pathItem = openapi.paths[path];
    const operation: any = {
      responses: {}
    };

    const pathParams = extractPathParams(path);
    if (pathParams.length > 0) {
      operation.parameters = pathParams.map(param => ({
        name: param,
        in: 'path',
        required: true,
        schema: { type: 'string' }
      }));
    }

    // Process responses
    for (const [statusCode, schemaBody] of Object.entries(entry.responseSchemas)) {
      operation.responses[statusCode] = {
        description: `Response for status ${statusCode}`,
        content: {
          'application/json': {
            schema: mapSchemaToOpenAPI(schemaBody)
          }
        }
      };
    }

    if (Object.keys(operation.responses).length === 0) {
      operation.responses['200'] = { description: 'Success' };
    }

    pathItem[method] = operation;
  }

  return openapi;
}
